### ISSUE TITLE
History and Context of Creation

### ISSUE THREAD

**Issue by Tcyla** [master-csmi/software-management-process-extremement-agile#3]
Agile Methods existed before the term was coined. Explain:
* What was their before ?
* How was written the agile manifesto ? 
* Why new development methodology were needed ?

**Comment by reneportillo23** [comment]
J'ai commencé un contexte historique. Je le finirai au plus vite en rajoutant :
- L'apparition des méthodes itératives dans le développement logiciel 
- La création en 2001 par 17 développeurs du Agile Manifesto
